const SUCCESS_CODE = 200;
const NOT_FOUND_ERROR = 404;
const INVALID_DATA_ERROR = 400;
const SERVER_ERROR = 500;

module.exports = {
  SUCCESS_CODE,
  NOT_FOUND_ERROR,
  INVALID_DATA_ERROR,
  SERVER_ERROR,
};
